trigger:
  branches:
    include:
      - main

variables:
  acrName: 'EventContainerTest'
  imageName: 'nacimeventscape'
  imageTag: '7'
  resourceGroup: 'EventBooking'
  appServiceName: 'EventScape'
  dockerfilePath: 'EventScape/Dockerfile'
  buildContext: 'EventScape'
  azureServiceConnection: 'eventbooking'       # ARM type
  acrServiceConnection: 'eventbookingdockerregistry'         # Docker Registry type

stages:

- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: Build
      displayName: 'Build and Push'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: '$(acrServiceConnection)'   # Docker Registry type
            repository: '$(imageName)'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            buildContext: '$(buildContext)'
            tags: |
              $(imageTag)

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: BuildAndPush
  jobs:
    - job: DeployJob
      displayName: 'Deploy to Web App'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureWebApp@1
          displayName: 'Deploy Container Image to Web App'
          inputs:
            azureSubscription: '$(azureServiceConnection)'
            appName: '$(appServiceName)'
            resourceGroupName: '$(resourceGroup)'
            deployToSlotOrASE: false
            appSettings: |
              -DOCKER_CUSTOM_IMAGE_NAME=$(acrName).azurecr.io/$(imageName):$(imageTag)