# Docker Build and Push to Azure Container Registry
# This pipeline builds a Docker image and pushes it to ACR

trigger:
  branches:
    include:
    - main

resources:
- repo: self

variables:
  # Container registry service connection (UPDATE THIS WITH YOUR ACTUAL SERVICE CONNECTION NAME)
  dockerRegistryServiceConnection: 'eventbookingdockerregistry'
  imageRepository: 'nacimeventscape'
  containerRegistry: 'eventcontainertest.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    
    # Debug: Show repository structure
    - script: |
        echo "Repository structure:"
        ls -la $(Build.SourcesDirectory)
        echo "Checking for Dockerfile:"
        if [ -f "$(Build.SourcesDirectory)/Dockerfile" ]; then
          echo "✅ Dockerfile found"
        else
          echo "❌ Dockerfile not found"
          exit 1
        fi
      displayName: 'Verify Dockerfile exists'
    
    # Build and push Docker image
    - task: Docker@2
      displayName: 'Build and push Docker image to ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    
    # Output image information
    - script: |
        echo "Image built and pushed:"
        echo "Registry: $(containerRegistry)"
        echo "Repository: $(imageRepository)"
        echo "Tag: $(tag)"
        echo "Full image name: $(containerRegistry)/$(imageRepository):$(tag)"
      displayName: 'Display image information'
