trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "=== MINIMAL PIPELINE 3 ==="
    echo "Build ID: $(Build.BuildId)"
    echo "Source: $(Build.SourcesDirectory)"
    ls -la
    echo "✅ Basic validation completed"
  displayName: 'Basic Validation'

- script: |
    echo "=== DOCKERFILE CHECK ==="
    if [ -f "Dockerfile" ]; then
      echo "✅ Dockerfile exists"
      echo "First 5 lines of Dockerfile:"
      head -5 Dockerfile
    else
      echo "❌ Dockerfile not found"
      exit 1
    fi
  displayName: 'Check Dockerfile'

- task: Docker@2
  displayName: 'Simple Docker Build'
  inputs:
    command: build
    dockerfile: 'Dockerfile'
    tags: 'test:$(Build.BuildId)'

- script: |
    echo "=== BUILD SUCCESS ==="
    echo "✅ Pipeline 3 completed successfully"
    echo "🎯 Docker image built without errors"
  displayName: 'Success Confirmation'