# Pipeline 3 - Local Build Only (Absolutely No Push)

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "=== PIPELINE 3 - LOCAL BUILD ONLY ===" && echo "NO REGISTRY OPERATIONS" && pwd && ls -la
  displayName: 'Environment Check'

- task: Docker@2
  displayName: 'Local Docker Build'
  inputs:
    command: 'build'
    dockerfile: 'Dockerfile'
    tags: 'local-build:$(Build.BuildId)'

- script: echo "✅ Local build completed - NO PUSH OPERATIONS"
  displayName: 'Build Complete'