# Simple Build Only Pipeline (No ACR Push)
# This pipeline builds the Docker image without pushing to avoid authentication issues

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Docker Image Only
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      vmImage: $(vmImageName)
    steps:
    
    # Verify repository structure
    - script: |
        echo "=== PIPELINE 3 - BUILD ONLY (NO PUSH) ==="
        echo "Checking repository structure:"
        ls -la $(Build.SourcesDirectory)
        echo "Verifying Dockerfile exists:"
        if [ -f "$(Build.SourcesDirectory)/Dockerfile" ]; then
          echo "✅ Dockerfile found"
        else
          echo "❌ Dockerfile missing"
          exit 1
        fi
        echo "Build tag: $(tag)"
      displayName: 'Verify Build Environment'
    
    # Build Docker image (no push, no authentication needed)
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          nacimeventscape:$(tag)
          nacimeventscape:latest
    
    # Display build information
    - script: |
        echo "=== BUILD COMPLETED SUCCESSFULLY ==="
        echo "✅ Docker image built successfully"
        echo "📦 Image: nacimeventscape:$(tag)"
        echo "📦 Latest: nacimeventscape:latest"
        echo "🎯 No authentication issues - build only pipeline"
        echo ""
        echo "To push to ACR, use pipeline 1 or 2 which have working authentication"
      displayName: 'Build Success Information'