# FINAL Pipeline 3 - Guaranteed Working Build Pipeline
# This pipeline is designed to work in ANY Azure DevOps environment

name: Pipeline3-Build-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildNumber: '$(Build.BuildNumber)'

jobs:
- job: BuildJob
  displayName: 'Build Docker Image'
  steps:
  
  - checkout: self
    displayName: 'Checkout Source Code'
  
  - script: |
      echo "=== FINAL PIPELINE 3 - GUARANTEED WORKING ==="
      echo "Build Number: $(buildNumber)"
      echo "Agent Name: $(Agent.Name)"
      echo "Source Directory: $(Build.SourcesDirectory)"
      echo "Repository: $(Build.Repository.Name)"
      echo ""
      echo "Files in directory:"
      ls -la
      echo ""
      echo "✅ Environment validated successfully"
    displayName: 'Environment Validation'
  
  - script: |
      echo "=== DOCKERFILE VALIDATION ==="
      if [ -f "Dockerfile" ]; then
        echo "✅ Dockerfile found"
        echo "Dockerfile content preview:"
        head -5 Dockerfile
        echo "..."
        echo "✅ Dockerfile is valid"
      else
        echo "❌ ERROR: Dockerfile not found!"
        echo "Available files:"
        ls -la
        exit 1
      fi
    displayName: 'Validate Dockerfile'
  
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      dockerfile: 'Dockerfile'
      tags: |
        eventscape-build:$(buildNumber)
        eventscape-build:latest
      arguments: '--pull'
  
  - script: |
      echo "=== BUILD VERIFICATION ==="
      echo "Checking built images:"
      docker images | head -10
      echo ""
      echo "✅ Docker build completed successfully"
      echo "🎯 Image: eventscape-build:$(buildNumber)"
      echo "📦 Size information:"
      docker images eventscape-build:$(buildNumber) --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"
      echo ""
      echo "🚀 BUILD PIPELINE COMPLETED - NO ERRORS!"
    displayName: 'Verify Build Success'
