# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EventScape

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: docker/login-action@v2
        with:
          registry: eventregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_E87DEC1D5E21483CAB99AA5DA04BF4DB }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_CF4A3C7816C7496A97DA6B8595901ABC }}
          

      - name: Build and Push container to registry
        run: |
          docker build -t eventregistry.azurecr.io/nacimeventscape:${{ github.sha }} .
          docker push eventregistry.azurecr.io/nacimeventscape:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_683AD8F2A7554A7C82995FF1CE9875E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A5D8C71E93E4EAA9AF93AC92343197B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1992D725C468483CBEF7D21B55B9AA73 }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'EventScape'
          slot-name: 'Production'
          images: 'eventregistry.azurecr.io/nacimeventscape:${{ github.sha }}'
          
